M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sat 24 Aug 2024 02:15:52 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-24T14:15:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1661
%
G90
G05
T1
X5.6028Y-5.299
X5.8303Y-5.299
T2
X5.198Y-5.4805
X5.3161Y-5.4805
T3
X3.6307Y-3.9331
X6.4378Y-3.2244
X6.4378Y-4.6417
M30
