version: '3'

services:
    workspace:
        image: ros2_workspace
        build:
            context: ..
            dockerfile: docker/ros2_workspace.Dockerfile
        tty: true # Prevent immediate exit when running with dev containers
        volumes:
            - ../little_red_rover_ws/src:/little_red_rover_ws/src
            - ../little_red_rover_ws/tools:/tools
            - ../assets:/assets
        ports:
            - "9002:9002" # gzweb
            - "9090:9090" # rosbridge
            - "8001:8001/udp" # microros agent -> microros client
    micro_ros_esp_idf:
        image: micro_ros_esp_idf
        tty: true # Prevent immediate exit when running with dev containers
        build:
            context: ..
            dockerfile: docker/micro_ros_esp_idf.Dockerfile
        privileged: true # Required to flash esp
        volumes:
            - ../esp32_firmware:/esp32_firmware
            - /dev:/dev
