version: '3'

services:
    workspace:
        image: ros2_workspace
        build:
            context: ..
            dockerfile: docker/ros2_workspace.Dockerfile
        tty: true # Prevent immediate exit when running with dev containers
        volumes:
            - ../little_red_rover_ws/src:/little_red_rover_ws/src
            - ../little_red_rover_ws/tools:/tools
        ports:
            - "9002:9002" # gzweb
            - "9090:9090" # rosbridge
            - "8001:8001/udp" # microros agent -> microros client
    micro_ros_esp_idf:
        image: micro_ros_esp_idf
        tty: true # Prevent immediate exit when running with dev containers
        build:
            context: ..
            dockerfile: docker/micro_ros_esp_idf.Dockerfile
        privileged: true # Required to flash esp
        volumes:
            - ../esp32_firmware:/esp32_firmware
            - /dev:/dev
    foxglove_bridge:
        image: foxglove_bridge
        build:
            context: ..
            dockerfile: docker/foxglove_bridge.Dockerfile
        ports:
            - "8765:8765"
    foxglove_studio:
        image: ghcr.io/foxglove/studio:latest
        container_name: foxglove
        ports:
            - "8080:8080"
    urdf_server:
        image: nginx:alpine
        volumes:
            - ../little_red_rover_ws/src/little_red_rover/assets:/usr/share/nginx/html
            - nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "8100:80"
