version: '3'

services:
    ros_iron_dev:
        image: ros_iron_dev
        build: 
          context: ../
          dockerfile: ./docker/ros_iron_dev/Dockerfile
        container_name: ros_iron_dev
        network_mode: host # --net:host
        ipc: host
        privileged: true # --privilaged
        tty: true
        depends_on:
          - micro_ros_iron_agent
        volumes:
          - ../little_red_rover_ws/src:/little_red_rover_ws/src
          - ../esp32_firmware:/microros_ws/firmware/freertos_apps/apps/esp32_firmware

    micro_ros_iron_agent:
        image: micro_ros_iron_agent
        build: ./micro_ros_iron_agent
        container_name: micro_ros_iron_agent
        network_mode: host # --net:host
        ipc: host
        privileged: true # --privilaged
        volumes:
            - /dev:/dev
              
    micro_ros_iron_flash:
        image: micro_ros_iron_flash
        build: 
          context: ../
          dockerfile: ./docker/micro_ros_iron_flash/Dockerfile
        container_name: micro_ros_iron_flash
        privileged: true # --privilaged
        volumes:
            - /dev:/dev
            - ../esp32_firmware:/microros_ws/firmware/freertos_apps/apps/esp32_firmware

    micro_ros_iron_firmware:
        image: micro_ros_iron_firmware
        build: ./micro_ros_iron_firmware
        container_name: micro_ros_iron_firmware

    ros_iron_base:
        image: ros_iron_base
        build: ./ros_iron_base
        container_name: ros_iron_base

