version: '3'

services:
    ros_iron_dev:
        image: ros_iron_dev
        build: ./ros_iron_dev
        container_name: ros_iron_dev
        network_mode: "host" # --net:host
        depends_on:
          - ros_iron_base
          - micro_ros_iron_agent
    micro_ros_iron_agent:
        image: micro_ros_iron_flash
        build: ./micro_ros_iron_agent
        container_name: micro_ros_iron_flash
        network_mode: "host" # --net:host
        privileged: true # --privilaged
        depends_on:
          - ros_iron_base
        volumes:
            - /dev:/dev
    micro_ros_iron_flash:
        image: micro_ros_iron_flash
        build: ./micro_ros_iron_flash
        container_name: micro_ros_iron_flash
        privileged: true # --privilaged
        depends_on:
          - ros_iron_base
        volumes:
            - /dev:/dev
    ros_iron_base:
        image: ros_iron_base
        build: ./ros_iron_base
        container_name: ros_iron_base
