M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Wed 24 Apr 2024 06:12:51 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-24T18:12:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0530
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1661
%
G90
G05
T1
X5.5083Y-5.3069
X5.7358Y-5.3069
T2
X7.9934Y-4.529
X8.0027Y-3.3371
T3
X3.6309Y-3.9331
X6.438Y-3.2244
X6.438Y-4.6417
M30
