M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Sun 21 Apr 2024 02:18:26 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-21T14:18:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0530
%
G90
G05
T1
X5.1224Y-5.3108
X5.35Y-5.3108
T2
X7.9934Y-4.529
X8.0027Y-3.3371
M30
