# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\")\n\tTimeStamp\x12\x0b\n\x03sec\x18\x01 \x01(\x05\x12\x0f\n\x07nanosec\x18\x02 \x01(\r\":\n\x08TwistCmd\x12\x18\n\x04time\x18\x01 \x01(\x0b\x32\n.TimeStamp\x12\t\n\x01v\x18\x02 \x01(\x02\x12\t\n\x01w\x18\x03 \x01(\x02\"\xda\x01\n\tLaserScan\x12\x18\n\x04time\x18\x01 \x01(\x0b\x32\n.TimeStamp\x12\x11\n\tangle_min\x18\x02 \x01(\x02\x12\x11\n\tangle_max\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ngle_increment\x18\x04 \x01(\x02\x12\x16\n\x0etime_increment\x18\x05 \x01(\x02\x12\x11\n\tscan_time\x18\x06 \x01(\x02\x12\x11\n\trange_min\x18\x07 \x01(\x02\x12\x11\n\trange_max\x18\x08 \x01(\x02\x12\x0e\n\x06ranges\x18\t \x03(\x02\x12\x13\n\x0bintensities\x18\n \x03(\x02\"i\n\x0bJointStates\x12\x18\n\x04time\x18\x01 \x01(\x0b\x32\n.TimeStamp\x12\x0c\n\x04name\x18\x02 \x03(\t\x12\x10\n\x08position\x18\x03 \x03(\x01\x12\x10\n\x08velocity\x18\x04 \x03(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x05 \x03(\x01\"\x9c\x01\n\tUdpPacket\x12\x1e\n\x05laser\x18\x01 \x01(\x0b\x32\n.LaserScanH\x00\x88\x01\x01\x12\'\n\x0cjoint_states\x18\x02 \x01(\x0b\x32\x0c.JointStatesH\x01\x88\x01\x01\x12\x1f\n\x07\x63md_vel\x18\x03 \x01(\x0b\x32\t.TwistCmdH\x02\x88\x01\x01\x42\x08\n\x06_laserB\x0f\n\r_joint_statesB\n\n\x08_cmd_velb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESTAMP']._serialized_start=18
  _globals['_TIMESTAMP']._serialized_end=59
  _globals['_TWISTCMD']._serialized_start=61
  _globals['_TWISTCMD']._serialized_end=119
  _globals['_LASERSCAN']._serialized_start=122
  _globals['_LASERSCAN']._serialized_end=340
  _globals['_JOINTSTATES']._serialized_start=342
  _globals['_JOINTSTATES']._serialized_end=447
  _globals['_UDPPACKET']._serialized_start=450
  _globals['_UDPPACKET']._serialized_end=606
# @@protoc_insertion_point(module_scope)
