version: '3'

services:
    workspace:
        image: ros2_workspace
        build:
            context: ..
            dockerfile: docker/ros2_workspace.Dockerfile
        tty: true # Prevent immediate exit when running with dev containers
        volumes:
            - ../src:/little_red_rover_ws/src
            - ../tools:/tools
        ports:
            - "9002:9002" # gzweb
            - "9090:9090" # rosbridge
            - "8001:8001/udp" # microros agent -> microros client
    foxglove_bridge:
        image: foxglove_bridge
        build:
            context: ../
            dockerfile: docker/foxglove_bridge.Dockerfile
        ports:
            - "8765:8765"
    urdf_server:
        image: nginx:alpine
        volumes:
            - ../src/little_red_rover/description/rover:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "8100:80"
